services:
  postgres:
    image: bitnami/postgresql
    container_name: db_postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=gerenciamento_projeto
    healthcheck:
          test: ["CMD-SHELL", "pg_isready -d gerenciamento_projeto -U postgres"] 
          interval: 10s
          timeout: 5s
          retries: 5
    volumes:
      - sistema_projeto:/bitnami/postgresql
volumes:
  sistema_projeto:
